Sandbox/wargo_02.xml

This is a practice pull request from class.

Sample Pull Request: XML Assignment 

---

Sandbox/Gardiner_TEI_EX3.xml
Sandbox/REVISEDGardiner_XSLT3.xsl

@ebeshero Hello, I added two example code documents from last semester!

Joey branch

---

Sandbox/ChickenRecipe.xml
Sandbox/SampleCodeTest.html

Hello, can you merge my branch to the main? Thanks

Zack dom branch

---

XML Assignments/hering_01.xml
XML Assignments/hering_02.xml

I fixed it so I am now merging my branch to the main branch

Logan branch

---

XML3-Homework/Gardiner_XML3.xml

Hello Dr. B! This branch included my xml3 assignment for Wednesday's homework.

Added my XML3 assignment

---

XML3-Homework/PatchNotes.xml

submitting XML-3 homework, adding file PatchNotes

---

XML3-Homework/Giles_Jan_26_Exercise_3.xml

hey @ebeshero please merge my branch. thank you!

julianXml3 branch

---

XML3-Homework/hering_03.xml

pushing my XML3 to the website (I also accidentally pushed a file into our main repo on my last branch pull request instead of the sandbox folder. So I deleted that in this push)

Logan XML3

---

XML3-Homework/erin_HW3.xml

Hello! Pull request: initiated

Erin Mooney XML_HW3

---

XML3-Homework/parrish_1-26_xml3.xml

@ebeshero this is my new pull request for the XML3 HW.

XML3 Homework

---

Class-Examples/XML/pituch3.xml

@ebeshero can I make this pull request

added my homework 3

---

GitHub-Test-3/tyler-gittest3.md

Please merge this branch into the remote repo :)

Tyler Cameron gittest3 pull request

---

GitHub-Test-3/GC-gitTest3.md

@ebeshero ask to merge it into the main branch.

a markdown for test 3

---

GitHub-Test-3/Gardiner_GitTest3.md

Hello, here is my git test 3 pull request!

Joey adding gitTest3 markdown file

---

GitHub-Test-3/jg-gitTest-3.md

Hey @ebeshero please merge my branch thanks.

adding git test 3 file

---

harrison-GitTest4.md

Hello everyone,
As a part of GitHub test 4, I was asking if someone could please pull my Markdown document into the main branch of the textAnalysis-Hub?
Thanks,
Harrison

I am commiting the Markdown file that is part of GitTest 4.

---

GitHub-Test-DHprojects/emilyGitHub3.md

Please merge my discussion post into the main branch for Git Test 4!

Canvas Discussion Markedown for Git Test 4

---

GitHub-Test-DHprojects/zmurphy-GitTest4.md

Hey @kmh6907 can you please commit my DH Project to the main branch:)

this is my DH Project discussion

---

GitHub-Test-DHprojects/Giles_Feb_6_gitTest4.md

@ebeshero please merge my branch, please! Thank you!

adding new mark down file

---

GitHub-Test-DHprojects/ZackDGitHubTest4.md

Hello, can merge my push, Thanks!

Submission of GitHub Test 4 for someone to Merge

---

GitHub-Test-DHprojects/logan-GitTest4.md

Can someone merge this pull request? Thanks!

Github test part 4

---

GitHub-Test-DHprojects/tyler-gittest4.md

Please merge this branch with the main repo for git test #4 :)

gittest4 md file from my discussion post responses

---

GitHub-Test-DHprojects/erinMooney-GitTest4.md

Hello there!
Please pull this branch :)

Erin Mooney contribution to the Project Discussion

---

GitHub-Test-DHprojects/hammer_gitTest4.md

Pull Request for GitTest04. If someone could merge this I would greatly appreciate it, lol!

Adding the Markdown file for Git Test 04

---

GitHub-Test-DHprojects/Gardiner_GitTest4.md

Hello, everyone If you could so kindly merge my branch to the main branch for the fourth git test, that would be greatly appreciated!

Joey adding git test number 4

---

GitHub-Test-3/Regex-step-file.md

@ebeshero this is my pull request for part 3 of the GitHub test.

part 3 of the GitHub test

---

GitHub-Test-3/graesyn_GitTest3.md

Here's my test stuff @ebeshero

adding markdown file

---

XML3-Homework/Cameron_03.xml

xml3+github practice

---

GitHub-Test-3/avrtest3.md

@ebeshero can you please approve this pull request?

git test 3

---

lilley_04_20_notes.md

I am commiting some notes that I took on 4/20/22.

---

AI-testing/AI-summaryTest/kupferChatGPT/husein-sama-chatGPT-Mistake.txt
AI-testing/AI-summaryTest/samChatGPT/husein-sama-chatGPT-Mistake.txt

@Seeedle ! This is the pull request we are opening.

Sam's ChatGPT2 branch ready to merge

---

AI-testing/remiorange-gpt2/ChatGPT2(1).txt
AI-testing/remiorange-gpt2/ChatGPT2(2).txt
AI-testing/remiorange-gpt2/ChatGPT2(3).txt

I've added 3 responses from ChatGPT and would like my work to be reviewed. Thanks!

Remington Orange Chat Test 2

---

Sandbox/FourthWall.txt
Sandbox/TimeTravel.txt

If anyone want to pull this request, feel free to do so.

branch for exercise 3

---

Sandbox/DIGIT_110/collection_tei.xsl

Here is some code from DIGIT 110 last semester, with the collection xslt my group created.

adding xslt to sandbox with new branch

---

GitHub-Test-3/hadleighMDtest.md

heyyyyyy please merge my thingy @ebeshero

git test for MD file

---

GitHub-Test-3/smassMDtest.md

adding my markdown file to the GitHub-Test-3 area

---

GitHub-Test-3/rorange - Copy.md

Sorry about that! Should be resolved now. Thanks for the help!

hopefully this will fix it GitTest3

---

GitHub-Test-3/wstiller-RAS.md

@ebeshero please merge this branch

wStiller GitHubTest-3

---

GitHub-Test-3/gittest3.md

add gittest 3

---

GitHub-Test-4-PyNLPDiscuss/gittest4 Markdown.md

add gittest4 markdown

---

GitHub-Test-4-PyNLPDiscuss/wstiller-GitTest4.md

@gak5275 Please merge this into main

wstiller github test 4

---

GitHub-Test-4-PyNLPDiscuss/gak-GitTest4.md

Anyone can feel free to pull this request for git test 5.

Gkupfer git test4

---

GitHub-Test-3/Jermaine-GitTest3.1
GitHub-Test-4-PyNLPDiscuss/GitTestMDjms9354.md

Hopefully this worked @ebeshero.

Jermaine git test4

---

GitHub-Test-3/Jermaine-GitTest3.1

I hopefully corrected my previous mistake @ebeshero

GitTest3.1

---

GitHub-Test-4-PyNLPDiscuss/rorange.md

GitTest4 Ready for merge! Thanks!

Submitting GitTest 4 Remington Orange

---

GitHub-Test-4-PyNLPDiscuss/nateHammer-GitTest4.md

Fixed the code block and added a link to documents for GitTest4

nateHammer Git Test 4 Assignment

---

GitHub-Test-4-PyNLPDiscuss/SMASS-MARKDOWN-4.md

adding my 4th test file from branch

---

GitHub-Test-4-PyNLPDiscuss/JordanJ-GitHubTest4.md

fixed the commit

---

Class-Examples/Python/readFileCollections-example/readingFileCollection.py
GitHub-Test-3/JordnanJ-GitHubTest3.md

This is the Test of the Third

---

GitHub-Test-3/scatledgeGitTest3.md

@ebeshero please merge my branch

Pushing git test part 3

---

GitHub-Test-4-PyNLPDiscuss/scatledgeGitTest4.md

Pushing part 4 of the git test

---

GitHub-Test-4-PyNLPDiscuss/Abele-GitTest4.md

@ebeshero could you please pull this to main!

md file added

---

Sandbox/drbTesterForBranch.txt

Hi @gylertaydos ! I'm requesting you to merge in my PR. Do this if you find I have not sent you malicious or otherwise unworthy material.

making a branch commit

---

AI-prompts/drb-tester.txt

@rcc5418 Notifying you that I'm sending a PR!

dr b test commit for branching in class

---

AI-prompts/ahopple/ahopple-chatgpt-results-2.txt
Sandbox/testingagain.txt
ahoppleTestingBranch.txt

Okay, here is my git pull request. I made a txt file and copied my AI prompt to a folder in the AI prompts folder in TextAnalysis-Hub but on my branch, and I also made a little txt file on my branch too. I don't know if I did this right...

branch commits

---

AI-prompts/khopple/khopple-chatgpt-2.txt
AI-prompts/khopple/khopple-claude-2.txt
Sandbox/example.txt
test.txt

This is a pull request to my new GitHub branch! Can you pull my branch into the main branch, please?

My new branch

---

AI-prompts/sammoniot/exercise2.txt

This is my chatgpt prompt response.

updated exercise 2

---

AI-prompts/OwenH/excercise1/chatgpt_experiment.txt
AI-prompts/OwenH/excercise1/claudeai_experiment.txt
AI-prompts/OwenH/excercise2/chatgpt_zuck.txt
AI-prompts/OwenH/excercise2/claudeai_zuck.txt
Sandbox/ohText.txt

Attempting to add a branch

---

AI-prompts/CalebKingAi/ClaudeAnagram
AI-prompts/CalebKingAi/GPTAnagram
AI-prompts/CalebKingAi/sci-fiEx2.txt

Hi professor! seems like the invite was the fix!

merge request with ai file & name

---

GitHub-Test-4/nlp_exercise_1.py

This is the fourth part of the GitHub Test, in which I had to modify some parts of a past homework assignment to make it write more accurate data.

GitHub Test 4

---

GitHub-Test-4/nlp2.py

Pull Request for GitTest4

---

GitHub-Test-3/rccMarkdown.md

@ebeshero Here is my pull request for Git Test Part 3

Git Test 3 complete

---

GitHub-Test-3/ahopple-GitTest3.md

Hello, @ebeshero ! This is Alyssa Hopple. I have made a pull request for the third part of the GitHub Test! Also, please take a look at my new markdown file that I made too! Thank you.

GitHub Test Part 3

---

GitHub-Test-3/mccolm-GitTest3/mccolm-digimon.md

Github Test 3

---

GitHub-Test-3/andrew-markdown.md

This branch adds my markdown file.

GitHub Test 3 - Andrew

---

GitHub-Test-3/gaydosGitTest3.md

I await you "marking down" my grade as 4/4 for this part of the test.

completion of Git Test part 3

---

GitHub-Test-3/sammoniotgittest3.md

Git Test 3 Pull Request

---

GitHub-Test-4/rcc-PythonNLPEx3.py

I encountered some odd errors where I couldn't git pull while in the branch, but I figured it out, I think.

Github test 4 complete

---

GitHub-Test-4/mccolm-GitTest4/Instructions.md
GitHub-Test-4/mccolm-GitTest4/PythonNLPEx3.py
GitHub-Test-4/mccolm-GitTest4/mccolm-GitTest4.py

Uploading Python Code

---

GitHub-Test-4/ahopple-nlpexercise1.py

Hello! This is my pull request for the fourth part of the GitHub Test. I decided to save my first Python exercise, which is about ChatGPT's take on recipe ideas themed around my favorite video game series, METROID, into my branch as I have done multiple new things to the spaCy codes for it! I also commented out which parts of the code I used and explained what they mean.

GitTest Part 4

---

SVG-Experiments/egv-svgmappy.svg

This is my very first pull request.

adding a cool SVG as a sample for branching and pull requests

---

SVG-Experiments/svg2_kranz.svg

added file for practice

---

SVG-Experiments/allgeier_svg2.svg

This is my pull request for the SVG + Git Branching Exercise assignment.

svg assingment 2

---

SVG-Experiments/simons_01-15_svg-01.svg

This is my pull request for the SVG + Git Branching Exercise assignment.

Michael's SVG Branch

---

Class-Examples/XSLT-to-SVG/Blobs.xml
Class-Examples/XSLT-to-SVG/XSLT-to-SVG-Orientation.md
Class-Examples/XSLT-to-SVG/blobs-to-SVG.xsl
Class-Examples/XSLT-to-SVG/magicEggs.svg

The class needs this branch for everyone to do the next homework assignment! Please pull this in, if it meets your approval.

Branch with XSLT to SVG Orientation and Exercise

---

SVG-Experiments/temiSVG/sakote_ex1.svg
SVG-Experiments/temiSVG/sakote_ex2.svg
SVG-Experiments/temiSVG/sakote_ex3.svg

SVG experiments folder

---

SVG-Experiments/mollywSVG/firstsvg.svg
SVG-Experiments/mollywSVG/genuary.svg
SVG-Experiments/mollywSVG/island.svg
SVG-Experiments/mollywSVG/island2.svg

This is my pull request for the SVG + Git Branching Exercise assignment. My branch contains the folder my SVG work up to now is contained in.

MollyW Pull Request

---

SVG-Experiments/svg-excersice-2-karmer.svg
gitBranching-Guide.md

For @ebeshero
I've created and branched the repo with the first draft of the branching guide. It's now in your hands to make any changes and fix any errors I didn't account for. Feel free to also add any commands I forgot about. I just have the feeling that I did somehow.

Git branch karmer

---

SVG-Experiments/eml-SVG/Larson_0114_svg01.svg
SVG-Experiments/eml-SVG/Larson_0116_svg02.svg
SVG-Experiments/eml-SVG/Larson_0119_svg02_redux.svg
SVG-Experiments/eml-SVG/islandAreas.svg

pull request for svg/branching assignment - EL

adding my svg's to the experiments folder using a branch - EL

---

SVG-Experiments/project2_MatthewWilpula.svg

My request to have my branch added to the main github for SVG + Git Branching Exercise.

Pushing my branch with SVG

---

SVG-Experiments/mishrasvg/svg_mishra-1.svg
SVG-Experiments/mishrasvg/svg_mishra-2.svg

pull request for mishrasvg file

adding mishrasvg file

---

XSLT-to-SVG/temi_xslt_svg/Blobs.xml
XSLT-to-SVG/temi_xslt_svg/Sakote_02.xml
XSLT-to-SVG/temi_xslt_svg/blob_svg3.xsl
XSLT-to-SVG/temi_xslt_svg/blobs.svg
XSLT-to-SVG/temi_xslt_svg/blobs_ex3.svg
XSLT-to-SVG/temi_xslt_svg/blobs_to_svg.xsl
XSLT-to-SVG/temi_xslt_svg/recipe.xsl
XSLT-to-SVG/temi_xslt_svg/recipe_xslt_svg.svg

pull request for the XSLT-to-SVG assignment

Added XSLT-to-SVG assignment

---

Installations/InstallNotes-Mac.md
Installations/InstallNotes-Win.md

Accidentally pushed this to Emma's branch... merging...

Installation notes for Mac and Windows: XProc and ixml

---

GitHub-Test-4/allgeier-mulan-string-2.xsl
GitHub-Test-4/simons_GitTest5.md

The file that I pushed was an xsl file for the Mulan screenplay analyze-string assingment.

This is a pull request for the GitHub Test Part 4

---

GitHub-Test-4/SVG2.xsl
GitHub-Test-4/mWrightTest5.md

XSLT file for part 4 of git test

---

GitHub-Test-3/testPart_3.md

New pull request for third part of the test.

markdown for part 3

---

GitHub-Test-3/sonnetSteps.md

this is my GitHub test 3 pull request

GitHubTest3

---

GitHub-Test-3/Digit496_Notes.md

Can you pull in my file and branch for GitHub test 3
code from bottom of instructions: 
<code att="cool">
<p>
</code>

pushing markdown file for github test 3

---

GitHub-Test-3/markdown_MatthewWilpula_GitTest3.md

My pull request for GitHub Test 3.

Matthew Wilpula Git Test 3 Pull Request
